name: ssdlc-sbom

permissions: {}

on:
  release:
    types: [published]

jobs:
  sbom:
    permissions:
      contents: write
    uses: mozilla/ssdlc-actions/.github/workflows/ssdlc-sbom.yml@aa759c845c83060e2473fd8df60f9f408e34675d # v1.2
    with:
      sbom_name: ai-scanner
